#!/bin/bash
#
# setup-base-system is a simple command to set up a base Debian 12/13 server.
#
# Copyright (C) 2022-2025 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/main/system/setup-base-system
#
# Usage:
#     bash -c "$(wget -qLO - https://raw.githubusercontent.com/alandoyle/helper-scripts/main/system/setup-base-system)"
# or
#     bash -c "$(curl -sSfL https://raw.githubusercontent.com/alandoyle/helper-scripts/main/system/setup-base-system)"
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi
#
################################################################################
#
if [ -f /etc/needrestart/needrestart.conf ] ; then
	echo "Setting 'needrestart' to AUTOMATIC"
	sed -i "/#\$nrconf{restart} = 'i';/s/.*/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf
fi
#
################################################################################
#
. /etc/os-release
if [ "${ID}" = "ubuntu" ] ; then
	echo "ERROR: Ubuntu is no longer supported."
    exit 98
fi
#
################################################################################
#
echo "Upgrade system (please be patient)"
apt-get update &>/dev/null
apt-get -y dist-upgrade &>/dev/null
#
################################################################################
#
echo "Adding additional applications"
NEW_APPS=exa
if [ "${VERSION_CODENAME}" = "trixie" ] ; then
   NEW_APPS="eza fastfetch"
fi
apt-get -y install ${NEW_APPS} vim aptitude lsscsi git curl gnupg p7zip p7zip-full unrar-free lm-sensors zip unzip btop iotop nala plocate rsync powertop command-not-found &>/dev/null
#
################################################################################
#
if [ ! -f /usr/bin/fastfetch ] ; then
    echo "Installing FASTFETCH (`uname -m`)"
    FASTFETCH_URL=https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-amd64.deb
    if [ "`uname -m`" = "aarch64" ] ; then
        FASTFETCH_URL=https://github.com/fastfetch-cli/fastfetch/releases/latest/download/fastfetch-linux-aarch64.deb
    fi
    curl --fail --silent --location --output /tmp/fastfetch-linux.deb "${FASTFETCH_URL}"
    dpkg -i /tmp/fastfetch-linux.deb &>/dev/null
fi
#
#################################################################################
#
echo "Configuring applications"
apt-file update &>/dev/null
update-command-not-found &>/dev/null
if [ !  -f /etc/vim/vimrc.local -a -d /etc/vim ] ; then
    cat <<EOF >/etc/vim/vimrc.local
if filereadable("\$VIMRUNTIME/defaults.vim")
  source \$VIMRUNTIME/defaults.vim
endif
" now set the line that the defaults file is not reloaded afterwards!
let skip_defaults_vim = 1
" turn off mouse
set mouse=
" other override settings go here
syntax on
EOF
fi
#
################################################################################
#
echo "Creating STARSHIP profiles"
cat <<EOF >/etc/starship.toml
# Simple starship.toml file
format = """
[ ](bg:#3B4252)\\
\$username\\
\$hostname\\
\$shell\\
[](fg:#3B4252 bg:#4C566A)\\
\$directory\\
[](fg:#4C566A bg:#86BBD8)\\
\$git_branch\\
\$git_commit\\
\$git_status\\
\$git_state\\
[](fg:#86BBD8)\\
\$sudo\\
\$nix_shell\\
\$cmd_duration\\
\$line_break\\
\$jobs\\
\$character\\
"""
command_timeout = 5000
add_newline = true

[username]
style_user = "white"
format = '[\$user](\$style bg:#3B4252)'

[hostname]
style = "bg:#3B4252"
format = "[@\$hostname ](\$style)"

[shell]
disabled = false
bash_indicator = ">_ "
fish_indicator = "><>"
zsh_indicator = "%_ "
powershell_indicator = ">>>"
cmd_indicator = "<<<"
unknown_indicator = "?_ "
style = "bg:#3B4252"
format = "[\$indicator](\$style)"

[directory]
truncation_length = 5
style = "bg:#4C566A"
format = "[ \$path ](\$style)"

[git_branch]
style = "bg:#86BBD8 fg:#3B4252"
format = '[ \$symbol$branch ](\$style)'

[git_commit]
style = "bg:#86BBD8 fg:#3B4252"
format = '[ \$hash ](\$style)'

[git_status]
style = "bg:#86BBD8 fg:#3B4252"
format = '[\$all_status\$ahead_behind](\$style)'

[git_state]
style = "bg:#86BBD8 fg:#3B4252"
format = '[ \$state(\$progress_current/\$progress_total)](\$style)'

[sudo]
allow_windows = true
disabled = false
symbol = '!'
style = 'bold green'
format = '[ \$symbol](\$style)'

[nix_shell]
impure_msg = '[❄️](bold blue)'
pure_msg = '[❄️](bold green)'
unknown_msg = '[❄️](bold yellow)'
format = ' \$state'

[cmd_duration]
min_time = 500
style = "fg:#eb7442"
format = " took [\$duration](\$style)"

[line_break]

[jobs]

[character]
success_symbol = '[-](bold green)'
# would be nice to have sudo module ehre
error_symbol = '[✕](bold red)'
vimcmd_symbol = '[N](bold blue) '
vimcmd_replace_one_symbol = '[R](bold red) '
vimcmd_replace_symbol = '[R](bold red) '
vimcmd_visual_symbol = "[V ](bold yellow)"
EOF
cat <<EOF >/etc/starship.root.toml
# Simple starship.toml file
format = """
[ ](bg:#5B0000)\\
\$username\\
\$hostname\\
\$shell\\
[](fg:#5B0000 bg:#A9191C)\\
\$directory\\
[](fg:#A9191C bg:#FF3535)\\
\$git_branch\\
\$git_commit\\
\$git_status\\
\$git_state\\
[](fg:#FF3535)\\
\$sudo\\
\$nix_shell\\
\$cmd_duration\\
\$line_break\\
\$jobs\\
\$character\\
"""
command_timeout = 5000
add_newline = true

[username]
style_user = "white"
format = '[\$user](\$style bg:#5B0000)'

[hostname]
style = "bg:#5B0000"
format = "[@\$hostname ](\$style)"

[shell]
disabled = false
bash_indicator = ">_ "
fish_indicator = "><>"
zsh_indicator = "%_ "
powershell_indicator = ">>>"
cmd_indicator = "<<<"
unknown_indicator = "?_ "
style = "bg:#5B0000"
format = "[\$indicator](\$style)"

[directory]
truncation_length = 5
style = "bg:#A9191C"
format = "[ \$path ](\$style)"

[git_branch]
style = "bg:#FF3535 fg:#5B0000"
format = '[ \$symbol\$branch ](\$style)'

[git_commit]
style = "bg:#FF3535 fg:#5B0000"
format = '[ \$hash ](\$style)'

[git_status]
style = "bg:#FF3535 fg:#5B0000"
format = '[\$all_status\$ahead_behind](\$style)'

[git_state]
style = "bg:#FF3535 fg:#5B0000"
format = '[ \$state(\$progress_current/\$progress_total)](\$style)'

[sudo]
allow_windows = true
disabled = false
symbol = '!'
style = 'bold red'
format = '[ \$symbol](\$style)'

[nix_shell]
impure_msg = '[❄️](bold blue)'
pure_msg = '[❄️](bold green)'
unknown_msg = '[❄️](bold yellow)'
format = ' \$state'

[cmd_duration]
min_time = 500
style = "fg:#eb7442"
format = " took [\$duration](\$style)"

[line_break]

[jobs]

[character]
success_symbol = '[-](bold green)'
# would be nice to have sudo module here
error_symbol = '[✕](bold red)'
vimcmd_symbol = '[N](bold blue) '
vimcmd_replace_one_symbol = '[R](bold red) '
vimcmd_replace_symbol = '[R](bold red) '
vimcmd_visual_symbol = "[V ](bold yellow)"
EOF

# Update /etc/skel
[ ! -d /etc/skel/.config ] && mkdir -p /etc/skel/.config
[ -f /etc/skel/.config/starship.toml ] && rm -f /etc/skel/.config/starship.toml
ln -sf /etc/starship.toml /etc/skel/.config/starship.toml
#
################################################################################
#

echo "Installing STARSHIP (`uname -m`)"
STARSHIP_URL=https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz
if [ "`uname -m`" = "aarch64" ] ; then
	STARSHIP_URL=https://github.com/starship/starship/releases/latest/download/starship-aarch64-unknown-linux-musl.tar.gz
fi
curl --fail --silent --location --output /tmp/starship.tar.gz "${STARSHIP_URL}"
tar xvf /tmp/starship.tar.gz >/dev/null 2>&1
[ -f /usr/local/bin/starship ] && rm -f /usr/local/bin/starship
mv starship /usr/local/bin/starship
chown root:root /usr/local/bin/starship
rm -f /tmp/starship.tar.gz
#
################################################################################
#
echo "Updating BASH profile"

# Fastfetch
[ -f /etc/profile.d/neofetch.sh ] && rm /etc/profile.d/neofetch.sh
cat <<EOF >/etc/profile.d/sysinfo.sh
if [ "\${SUDO_USER}" = "" ] ; then
    clear
    fastfetch
    if [ -f /usr/bin/incus ] ; then
        echo -e "\n\tINCUS CONTAINERS"
        incus ls -cns4
    fi
    if [ -f /usr/bin/docker ] ; then
        echo -e "\n\tDOCKER CONTAINERS\n-------------------------------------------------------------------------------"
        docker ps --format "table {{.Names}}\t{{.State}}\t{{.Status}}\t{{.Ports}}"
    fi
    if [ -f /usr/sbin/pct ] ; then
        echo -e "\n\tLXC CONTAINERS\n-------------------------------------------------------------------------------"
        sudo /usr/sbin/pct list
    fi
    if [ -f  /usr/sbin/qm ] ; then
        echo -e "\n\tKVM MACHINES\n-------------------------------------------------------------------------------"
        sudo /usr/sbin/qm list
    fi
fi

EOF

# Terminal
cat <<EOF >/etc/profile.d/term.sh
if [ -z \${SSH_TTY} ] ; then
	export TERM=linux
fi
EOF

# Quoting Style
echo "export QUOTING_STYLE=literal" > /etc/profile.d/quoting_style.sh

# Starship
cat <<EOF >/etc/profile.d/starship.sh
tty | grep tty >/dev/null

# Only display for remote connections
if [ -f /usr/local/bin/starship -a \$? -ne 0 ] ; then
	[ ! -d ~/.config ] && mkdir -p ~/.config
	[ -f ~/.config/starship.toml ] && rm -f ~/.config/starship.toml
	if [ \`id -u\` -eq 0 ] ; then
		ln -sf /etc/starship.root.toml ~/.config/starship.toml
	else
		ln -sf /etc/starship.toml ~/.config/starship.toml
	fi
	eval "\$(starship init bash)"
fi
EOF

# Check if we're installing on Debian as it has a different /root/.bashrc to Ubuntu
grep "PROFILE UPDATE" /root/.bashrc >/dev/null 2>&1
if [ $? -ne 0 -a "${ID}" = "debian" ] ; then
	echo "Updating /root/.bashrc"
	echo -e "#\n# PROFILE UPDATE\nps -p 2 >/dev/null # LXD Container check\nif [ \$? -ne 0 -o \"\${SUDO_USER}\" != \"\" ] ; then\n\t. /root/.bash_aliases\nfi" >> /root/.bashrc
fi
#
################################################################################
#
echo "Configuring BASH aliases"
grep -F bash.aliases /root/.bashrc &>/dev/null 2>&1
if [ $? -eq 0 ] ; then
	# Remove old modifications
 	cat /root/.bashrc | grep -v 'bash\.aliases' > /root/.bashrc.$$
	mv /root/.bashrc.$$ /root/.bashrc
fi
echo "[ -f /etc/bash.aliases ] && . /etc/bash.aliases" > /etc/profile.d/aliases.sh
cat <<EOF >/etc/bash.aliases

alias dfspace='df -hT -x udev -x tmpfs -x cgmfs -x snap -x devtmpfs -x fuse -x overlay -x efivarfs'
alias pg='less'
alias cls='clear'
alias btop='btop --utf-force'
alias goroot='sudo -s'
alias go64='sudo -s'

# Change directory aliases
alias home='cd ~'
alias cd..='cd ..'

# cd into the old directory
alias bd='cd "\$OLDPWD"'

# Remove a directory and all files
alias rmd='/bin/rm  --recursive --force --verbose '

# Alias's for multiple directory listing commands
alias ls='exa -H --group-directories-first'
alias la='exa -alh' # show hidden files
alias lf='exa -aFh --color=always' # add colors and file type extensions
alias lx='exa -l --sort=ext' # sort by extension
alias lk='exa -l --sort=size' # sort by size
alias lc='exa -l --sort=mod' # sort by modified time
alias lu='exa -l --sort=acc' # sort by access time
alias lr='exa -lR' # recursive ls
alias lt='exa -l --sort=new' # sort by date
alias lm='exa -al |more' # pipe through 'more'
alias lw='exa -xa' # wide listing format
alias ll='exa -alF --group-directories-first' # long listing format
alias labc='exa -l --sort=name' #alphabetical sort
alias lff="exa -l | egrep -v '^d'" # files only
alias ldir="exa -l | egrep '^d'" # directories only

# Search command line history
alias h='history | grep '

# Alias's for archives
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

# Extracts any archive(s) (if unp isn't installed)
extract () {
	for archive in "\$@"; do
		if [ -f "\$archive" ] ; then
			case \$archive in
				*.tar.bz2)   tar xvjf \$archive    ;;
				*.tar.gz)    tar xvzf \$archive    ;;
				*.bz2)       bunzip2 \$archive     ;;
				*.rar)       unrar -x \$archive    ;;
				*.gz)        gunzip \$archive      ;;
				*.tar)       tar xvf \$archive     ;;
				*.tbz2)      tar xvjf \$archive    ;;
				*.tgz)       tar xvzf \$archive    ;;
				*.zip)       unzip \$archive       ;;
				*.Z)         uncompress \$archive  ;;
				*.7z)        7z x \$archive        ;;
				*)           echo "don't know how to extract '\$archive'..." ;;
			esac
		else
			echo "'\$archive' is not a valid file!"
		fi
	done
}

# Disk usage support
alias used='du -sh'
alias usedm='du -s --block-size=1M'
alias usedg='du -s --block-size=1G'

# sudo quick shortcuts
alias reboot='sudo /usr/sbin/reboot'
alias su-vi='sudo vi'
alias su-nano='sudo nano'
alias su-rm='sudo rm'
alias su-cp='sudo cp'
alias su-mv='sudo mv'
alias su-md='sudo mkdir -p'
alias dmesg='sudo /usr/bin/dmesg'
alias mount='sudo /usr/bin/mount'
alias umount='sudo /usr/bin/umount'
alias iotop='sudo /usr/sbin/iotop'
alias apt='sudo nala'
alias powertop='sudo /usr/sbin/powertop'
alias systemctl='sudo /usr/bin/systemctl'

EOF

# Create a new .bash_aliases for root
cat <<EOF >/root/.bash_aliases
ps -p 2 >/dev/null # LXD Container check
if [ \$? -ne 0 -o "\${SUDO_USER}" != "" ] ; then
	. /etc/profile
fi
EOF
#
################################################################################
#
echo "Creating Update Script (/usr/local/bin/update-base-system)"
cat <<EOF >/usr/local/bin/update-base-system
#!/bin/bash
#
# Update System
#
echo "Updating BASE system..."
sudo bash -c "\$(wget -qLO - https://raw.githubusercontent.com/alandoyle/helper-scripts/main/system/setup-base-system)"
#
# Update INCUS if it is installer
#
if [ -f /usr/bin/incus ] ; then
	echo "Updating INCUS..."
	sudo bash -c "\$(wget -qLO - https://github.com/alandoyle/helper-scripts/raw/main/installers/incus-installer)" &>/dev/null
	echo "Incus v\`incus --version\` installed."
	echo "Logout and back in again to complete install."
fi
#
# Update DOCKER if it is installer
#
if [ -f /usr/bin/docker ] ; then
	echo "Updating DOCKER..."
	sudo bash -c "\$(wget -qLO - https://github.com/alandoyle/helper-scripts/raw/main/installers/docker-installer)" &>/dev/null
	echo "\`docker --version\` installed."
	echo "Logout and back in again to complete install."
fi
EOF
chmod a+x /usr/local/bin/update-base-system
#
################################################################################
#
if [ ! -f /var/lib/plocate/plocate.db ] ; then
	echo "Updating plocate.db"
	updatedb
fi
#
################################################################################
#
for USERNAME in $(ls -1 /home)
do
    USERHOMEDIR=/home/${USERNAME}
	USERUID=`grep ${USERHOMEDIR} /etc/passwd | cut -d: -f3`
	USERGID=`grep ${USERHOMEDIR} /etc/passwd | cut -d: -f4`
	echo "Setting .hushlogin for ${USERNAME} (${USERHOMEDIR})"
	touch ${USERHOMEDIR}/.hushlogin
	chown ${USERUID}:${USERGID} ${USERHOMEDIR}/.hushlogin
done

if [ ! -z ${USERHOMEDIR} -a ! -f ${USERHOMEDIR}/.hushlogin ] ; then
	echo "Setting .hushlogin for ${SUDO_USER} (${USERHOMEDIR})"
	touch ${USERHOMEDIR}/.hushlogin
	chown ${SUDO_USER}:${SUDO_USER} ${USERHOMEDIR}/.hushlogin
fi
if [ ! -f /root/.hushlogin ] ; then
	echo "Setting root .hushlogin"
	touch /root/.hushlogin
fi
if [ ! -f /etc/skel/.hushlogin ] ; then
	echo "Setting default .hushlogin"
	touch /etc/skel/.hushlogin
fi
#
################################################################################
