#!/bin/bash
#
# certbot-cloudflare-installer is a simple installer for Certbot with Cloudflare DNS-01 auth method.
#
# Copyright (C) 2024-2025 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
#
# Install using:
#     sudo bash -c "$(wget -qLO - https://github.com/alandoyle/helper-scripts/raw/main/installers/certbot-cloudflare-installer)"
# or
#     sudo bash -c "$(curl -sSfL https://github.com/alandoyle/helper-scripts/raw/main/installers/certbot-cloudflare-installer)"
#
################################################################################
#
# Sudo check
#
if [ "$SUDO_USER" = "" ] ; then
    echo "ERROR: This script needs to be run using sudo."
    exit 99
fi
#
################################################################################
#
# Install Certbot and Cloudflare Plugin via Docker
#
if [ ! -f /usr/bin/docker ] ; then
    echo "Installing Docker..."
    bash -c "$(wget -qLO - https://github.com/alandoyle/helper-scripts/raw/main/installers/docker-installer)"
fi

echo "Installing Cerbot Cloudflare Docker system..."
bash -c "$(wget -qLO - https://raw.githubusercontent.com/alandoyle/docker-cloudflare-certbot/main/install)"
#
################################################################################
