#!/bin/bash
#
# docker-installer is a simple installer for the Brave browser.
# 
# Copyright (C) 2022 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi

################################################################################
#
# Setup
#
apt install apt-transport-https ca-certificates curl software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
apt update
apt install docker-ce -y
usermod -aG docker ${USER}


LOCATION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest \
| grep -v sha256 \
| grep -i "browser_download_url.*`uname -s`-`uname -p`" \
| awk '{ print $2 }' \
| sed 's/,$//' \
| sed 's/"//g' )

curl -sSL ${LOCATION} -o /usr/libexec/docker/cli-plugins/docker-compose
chmod a+x /usr/libexec/docker/cli-plugins/docker-compose

docker compose version
