#!/bin/bash
#
# docker-installer is a simple installer for Docker.
# 
# Copyright (C) 2022 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi

################################################################################
#
# Setup
#
apt install apt-transport-https ca-certificates curl software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
apt update

################################################################################
#
# Install docker and plugins
#
apt install docker-ce docker-compose-plugin docker-scan-plugin -y

################################################################################
#
# Add local user to docker group (only for new shells)
#
usermod -aG docker ${SUDO_USER}

################################################################################
#
# Create docker-compose shim
#
cat << EOF | tee /usr/local/bin/docker-compose >/dev/null
#
# docker-compose shim
#
docker compose "\$@"
EOF
chmod a+x /usr/local/bin/docker-compose
docker-compose version
