#!/bin/bash
#
# docker-installer is a simple installer for Docker.
#
# Copyright (C) 2022-2025 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/
#
# Install using:
#     sudo bash -c "$(wget -qLO - https://github.com/alandoyle/helper-scripts/raw/main/installers/docker-installer)"
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi


################################################################################
#
# Additional Software list
#
. /etc/os-release
SW_COMMON=
[ "${VERSION_CODENAME}" != "trixie" ] && SW_COMMON=software-properties-common

################################################################################
#
# Setup
#
apt install apt-transport-https ca-certificates curl ${SW_COMMON} -y
[ -f /usr/share/keyrings/docker-archive-keyring.gpg ] && rm -f /usr/share/keyrings/docker-archive-keyring.gpg
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/$(lsb_release -is|awk '{print tolower($0)}') $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
apt update

################################################################################
#
# Install docker and plugins
#
apt install docker-ce docker-compose-plugin docker-buildx-plugin yamllint -y

################################################################################
#
# Add local user to docker group (only for new shells)
DOCKER_USER=${SUDO_USER}
[ -z ${DOCKER_USER} ] && DOCKER_USER=${USER}
usermod -aG docker ${DOCKER_USER}

################################################################################
#
# Add Docker aliases
#
cat << EOF | tee /etc/profile.d/docker.sh >/dev/null
#
# Docker Aliases
#
alias dkup='docker compose up -d'
alias dkdn='docker compose down'
alias dkps='docker ps --format "table {{.Names}}\t{{.State}}\t{{.Status}}\t{{.Ports}}"'
alias dkrs='docker compose down && docker compose up -d'
function dkxc() {
    docker exec -it "\$1" /bin/sh
}
EOF

################################################################################
#
# Create docker-compose shim
#
cat << EOF | tee /usr/local/bin/docker-compose >/dev/null
#
# docker-compose shim
#
docker compose "\$@"
EOF
chmod a+x /usr/local/bin/docker-compose
docker-compose version
