#!/bin/bash
#
# incus-installer is a simple installer for Incus.
#
# Copyright (C) 2024-2026 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
#
# Install using:
#     sudo bash -c "$(wget -qLO - https://github.com/alandoyle/helper-scripts/raw/main/installers/incus-installer)"
# or
#     sudo bash -c "$(curl -sSfL https://github.com/alandoyle/helper-scripts/raw/main/installers/incus-installer)"
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi

################################################################################
#
# Debian 12 (or higher) check
#
VERSION_ID="0"
VERSION_CODENAME=unknown
ID=unknown
. /etc/os-release
if [ "${ID}" != "debian" -a $VERSION_ID -lt 12 ] ; then
    echo "ERROR: This script needs to be run on Debian 12 (bookworm) or higher."
    exit 98
fi

################################################################################
#
# Add the Zabbly Stable Repo (https://github.com/zabbly/incus/tree/stable)
#
# Stable packages provide by Stéphane Graber, one of the core Incus developers.
# This repo provides more up-to-date versions of Incus than the main Distro.
#
wget -O /etc/apt/keyrings/zabbly.asc https://pkgs.zabbly.com/key.asc
cat <<EOF > /etc/apt/sources.list.d/zabbly-incus-stable.sources
Enabled: yes
Types: deb
URIs: https://pkgs.zabbly.com/incus/stable
Suites: $(. /etc/os-release && echo ${VERSION_CODENAME})
Components: main
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/zabbly.asc
EOF

################################################################################
#
# Make sure system is up-to-date before continuing
#
apt update && apt upgrade -y

################################################################################
#
# Install Incus Base (as per https://discuss.linuxcontainers.org/t/incus-deinstalled-after-upgrade-in-debian-bookworm-with-backports/23209)
#
apt install bridge-utils incus-base -y

################################################################################
#
# Prevent connectivity issues with Incus and Docker (also needed for Armbian if using ifupdown instead of NetworkManager)
# https://linuxcontainers.org/incus/docs/main/howto/network_bridge_firewalld/#prevent-connectivity-issues-with-incus-and-docker
#
echo "net.ipv4.conf.all.forwarding=1" > /etc/sysctl.d/99-forwarding.conf
systemctl restart systemd-sysctl

################################################################################
#
# Add local user to incus-admin group (only for new shells)
#
INCUS_USER=${SUDO_USER}
[ -z ${INCUS_USER} ] && INCUS_USER=${USER}
usermod -aG incus-admin ${INCUS_USER}

################################################################################
#
# Add Incus aliases
#
cat << EOF | tee /etc/profile.d/incus.sh >/dev/null
. /etc/os-release
#
# Incus Aliases
#
alias lslx='incus ls -cns4 -f compact|egrep "RUNNING|STOPPED"'
alias lslx6='incus ls -cns6 -f compact|egrep "RUNNING|STOPPED"'
alias lxc='incus'
alias lxls='incus ls -cns4 -f compact|egrep "RUNNING|STOPPED"'
alias lxls6='incus ls -cns6 -f compact|egrep "RUNNING|STOPPED"'
alias lxps='incus ls -cns46 -f compact'
alias lxrm='incus delete'
alias lxup='incus start'
alias lxdn='incus stop'
alias lxrs='incus restart'
function lxxc() {
        incus exec \${1} /bin/bash
}
function lxdknew() {
        lxnew \${1} ENABLE
}
function lxdel() {
        incus stop \${1}
        incus delete \${1}
}
EOF

################################################################################
#
# Add Incus lxnew script
#
cat << EOF | tee /usr/local/bin/lxnew >/dev/null
#!/bin/bash
#
# lxnew is a simple command to set up an INCUS container.
#
# Copyright (C) 2025-2026 Alan Doyle
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi
#
################################################################################
#
. /etc/os-release
#
################################################################################
#
LXNEW_EXTRA=
CONTAINER_NAME=$1
USE_DOCKER=$2
if [ "${CONTAINER_NAME}" = "" ] ; then
    echo "ERROR: A container name is required!"
    exit 98
fi
#
################################################################################
#
echo "Creating ${CONTAINER_NAME}..."
incus launch images:debian/${VERSION_ID} ${CONTAINER_NAME}
#
################################################################################
#
if [ "${USE_DOCKER}" != "" ] ; then
    echo "- Enabling Docker support"
    incus config set ${CONTAINER_NAME} security.nesting=true security.syscalls.intercept.mknod=true security.syscalls.intercept.setxattr=true
fi
#
################################################################################
#
echo "- Prepping Server"
incus exec ${CONTAINER_NAME} -- /usr/bin/apt update
incus exec ${CONTAINER_NAME} -- /usr/bin/apt upgrade -y
incus exec ${CONTAINER_NAME} -- /usr/bin/apt install wget curl openssh-server -y
#
################################################################################
#
STORAGE_POOL=`incus storage show default | grep source: | cut -d' ' -f4`
WGETRC=${STORAGE_POOL}/containers/${CONTAINER_NAME}/rootfs/etc/wgetrc
echo "- Force wget to IPv4 only"
grep inet4_only ${WGETRC} >/dev/null 2>&1
if [ $? -ne 0 ] ; then
    echo -e "\n# Force IPv4\ninet4_only = on\n" >> ${WGETRC}
fi
#
################################################################################
EOF
chmod a+x /usr/local/bin/lxnew

################################################################################
#
# Set up the system as per https://documentation.ubuntu.com/lxd/stable-4.0/production-setup/
#
[ -f /etc/security/limits.conf.ORIG ] && mv /etc/security/limits.conf.ORIG /etc/security/limits.conf

if [ ! -f /etc/security/limits.d/99-limits.conf ] ; then
    echo "Creating /etc/security/limits.d/99-limits.conf..."
    cat << EOF | tee /etc/security/limits.d/99-limits.conf >/dev/null
# /etc/security/limits.conf
#
#<domain> <type> <item> <value>
*    soft     nproc          1048576
*    hard     nproc          1048576
*    soft     nofile         1048576
*    hard     nofile         1048576
*    soft     memlock        unlimited
*    hard     memlock        unlimited
root soft     nproc          unlimited
root hard     nproc          unlimited
root soft     nofile         unlimited
root hard     nofile         unlimited
# End of file
EOF
fi

echo "Updating SYSCTL Settings..."
if [ ! -f /etc/sysctl.d/99-fs.conf ] ; then
    echo "- Creating /etc/sysctl.d/99-fs.conf..."
    cat > /etc/sysctl.d/99-fs.conf << EOF
fs.nr_open = 12000000
fs.file-max = 9223372036854775807
fs.aio-max-nr = 1048576
EOF
fi

if [ ! -f /etc/sysctl.d/99-inotify.conf ] ; then
    echo "- Creating /etc/sysctl.d/99-inotify.conf..."
    cat > /etc/sysctl.d/99-inotify.conf << EOF
fs.inotify.max_queued_events=1048576
fs.inotify.max_user_instances=1048576
fs.inotify.max_user_watches=1048576
EOF
fi

if [ ! -f /etc/sysctl.d/99-maxkeys.conf ] ; then
    echo "- Creating /etc/sysctl.d/99-maxkeys.conf..."
    cat > /etc/sysctl.d/99-maxkeys.conf << EOF
kernel.keys.maxbytes=100000000
kernel.keys.root_maxkeys=1000000
kernel.keys.maxkeys=1000000
EOF
fi

if [ ! -f /etc/sysctl.d/99-memory.conf ] ; then
    echo "- Creating /etc/sysctl.d/99-memory.conf..."
    cat <<EOF > /etc/sysctl.d/99-memory.conf
# Balanced Memory Optimization
vm.swappiness = 10
vm.dirty_ratio = 15
vm.dirty_background_ratio = 5
vm.overcommit_memory = 1
vm.max_map_count = 262144
EOF
fi

SYSCTL_FILE=/etc/sysctl.d/99-incus.conf
echo "Creating /etc/sysctl.d/99-incus.conf..."
cat << EOF > /etc/sysctl.d/99-incus.conf
# Incus Settings
#
kernel.dmesg_restrict=1
net.ipv4.neigh.default.gc_thresh3=8192
net.ipv6.neigh.default.gc_thresh3=8192
# End of file
EOF

################################################################################
#
# Show Incus version
#
echo "Incus v`incus --version` installed."
echo "Please 'reboot' to complete install."
