#!/bin/bash
#
# pihole-installer is a simple installer for the PiHole 6 with a Cloudflare
# backend connecting over a cloudflare tunnel to Cloudflare's DoH (DNS over
# HTTPS) servers.
#
# It also supports a custom hosts file (/etc/hosts.lan) which it will import
# into /etc/pihole/hosts/custom.list
#
# Copyright (C) 2022-2025 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
#
# Install using:
#     sudo bash -c "$(wget -qLO - https://github.com/alandoyle/helper-scripts/raw/main/installers/pihole-installer)"
# or
#     sudo bash -c "$(curl -sSfL https://github.com/alandoyle/helper-scripts/raw/main/installers/pihole-installer)"
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi

################################################################################
# Include OS details
. /etc/os-release

################################################################################
# Make sure `curl' is installed
apt update
apt install curl -y

################################################################################
# Install cloudflared
if [ ! -f /lib/systemd/system/cloudflared.service ] ; then
        ########################################################################
        # Add cloudflared user
        useradd -s /usr/sbin/nologin -r -M cloudflared
        ########################################################################
        # Add cloudflared configuration
        cat << EOF > /etc/default/cloudflared
# Commandline args for cloudflared
#
# Standard DNS:     1.1.1.1 & 1.0.0.1
# Malware Blocking: 1.1.1.2 & 1.0.0.2
# Malware & Porn:   1.1.1.3 & 1.0.0.3
#
CF_PRIMARY=1.1.1.1
CF_SECONDARY=1.0.0.1
CLOUDFLARED_OPTS=--port 5053 --upstream https://\${CF_PRIMARY}/dns-query --upstream https://\${CF_SECONDARY}/dns-query
EOF
        ########################################################################
        # Generate systemd unit file
        cat << EOF > /lib/systemd/system/cloudflared.service
[Unit]
Description=cloudflared DNS over HTTPS proxy
After=syslog.target network-online.target

[Service]
Type=simple
User=cloudflared
EnvironmentFile=/etc/default/cloudflared
ExecStart=/usr/bin/cloudflared proxy-dns \$CLOUDFLARED_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target
EOF
        ########################################################################
        # Add cloudflare gpg key
        curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null

        ########################################################################
        # Add this repo to your apt repositories
        echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared ${VERSION_CODENAME} main" | sudo tee /etc/apt/sources.list.d/cloudflared.list >/dev/null

        ########################################################################
        # install cloudflared
        apt update && apt install cloudflared -y

        ########################################################################
        # Set permissions
        chown cloudflared:cloudflared /etc/default/cloudflared
        #chown cloudflared:cloudflared /usr/bin/cloudflared
        #chmod a+x /usr/bin/cloudflared
        ########################################################################
        # Enable systemd service
        systemctl enable cloudflared
        systemctl start cloudflared
fi

################################################################################
# Setup Pi-Hole 6
if [ ! -f /etc/pihole/pihole.toml ] ; then
        ########################################################################
        # Install Pi-Hole
        PIHOLE_SKIP_OS_CHECK=true bash -c "$(curl -sSfL https://install.pi-hole.net)"
fi

################################################################################
# Basic Pi-Hole configuration
pihole setpassword
#pihole -w analytics.twitter.com dl.delivery.mp.microsoft.com geo-prod.do.dsp.mp.microsoft.com spclient.wg.spotify.com
#pihole -b activity.windows.com msedge.net assets.msn.com edge.microsoft.com
sleep 5

################################################################################
# Configure Pi-Hole to use cloudflared
pihole-FTL --config dns.upstreams '[ "127.0.0.1#5053" ]'

################################################################################
# Enable dnsmasq.d support in pihole 6
pihole-FTL --config misc.etc_dnsmasq_d true

################################################################################
# Setup reasonable TTL
cat << EOF > /etc/dnsmasq.d/09-ttl.conf
# See https://00f.net/2019/11/03/stop-using-low-dns-ttls/ for more rational.
min-cache-ttl=2400
EOF

################################################################################
# Setup an additional "Local DNS" host file
cat << EOF > /etc/dnsmasq.d/09-localdns.conf
# Add additional hosts here for local DNS resolution.
EOF

################################################################################
# Reboot
reboot
