#!/bin/bash
#
# powersaver-installer is a Configurable PowerSaver installer.
# 
# Copyright (C) 2022 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/
# 
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
#
# Install using:
#     sudo bash -c "$(wget -qLO - https://github.com/alandoyle/helper-scripts/raw/main/installers/powersaver-installer)"
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi

################################################################################
#
# Install prerequisites
#
apt -y install powertop

################################################################################# Create scripts
#
# Create scripts
#
cat << EOF > /usr/sbin/init-powersaver
#!/bin/sh
#
# Initialise PowerSaver
# 
# Copyright (C) 2022 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/
#
################################################################################
#
# Root check
#
if [ \`id -u\` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi

################################################################################
#
# Enable all PowerTOP savings
#
/usr/sbin/powertop --auto-tune

################################################################################
#
# Include any system specific powersaving
#
[ -f "/etc/powersaver.d/custom-rules.conf" ] && . "/etc/powersaver.d/custom-rules.conf"

EOF

################################################################################
# Create config
#
[ ! -d /etc/powersaver.d ] && mkdir -p /etc/powersaver.d

if [ ! -f /etc/powersaver.d/custom-rules.conf ] ; then
    cat << EOF > /etc/powersaver.d/custom-rules.conf
#
# Additional PowerSaver Rules
#
################################################################################

EOF
fi

################################################################################
# Set permissions
#
chmod 755 /usr/sbin/init-powersaver
chmod 644 /etc/powersaver.d/custom-rules.conf


################################################################################
# Create systemd service
#
cat << EOF > /etc/systemd/system/powersaver.service
[Unit]
Description=Configurable PowerSaver service
[Service]
ExecStart=/usr/sbin/init-powersaver
Type=oneshot
RemainAfterExit=true
[Install]
WantedBy=multi-user.target
EOF

################################################################################
# Install service
#
systemctl daemon-reload
systemctl enable powersaver
systemctl start powersaver
