#!/bin/bash
#
# webmin-installer is a simple installer for Webmin.
#
# Copyright (C) 2025 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
#
# Install using:
#     sudo bash -c "$(wget -qLO - https://raw.githubusercontent.com/alandoyle/helper-scripts/main/installers/webmin-installer)"
# or
#     sudo bash -c "$(curl -sSfL https://raw.githubusercontent.com/alandoyle/helper-scripts/main/installers/webmin-installer)"
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi

################################################################################
#
# Pre-requisites
#
apt-get update
apt-get install curl wget -y

################################################################################
#
# Run the setup official script
#
bash -c "$(wget -qLO - https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh)"
apt-get install --install-recommends webmin usermin -y
#
################################################################################
