#!/bin/bash
#
# xanmod-edge-installer is a simple installer for the Xanmod Edge kernel.
# 
# Copyright (C) 2022 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi

################################################################################
#
# Get PACKAGE to install. 
#
function get_package()
{
	/usr/bin/awk 'BEGIN {
	    while (!/flags/) if (getline < "/proc/cpuinfo" != 1) exit 1
	    if (/lm/&&/cmov/&&/cx8/&&/fpu/&&/fxsr/&&/mmx/&&/syscall/&&/sse2/) level = 1
	    if (level == 1 && /cx16/&&/lahf/&&/popcnt/&&/sse4_1/&&/sse4_2/&&/ssse3/) level = 2
	    if (level == 2 && /avx/&&/avx2/&&/bmi1/&&/bmi2/&&/f16c/&&/fma/&&/abm/&&/movbe/&&/xsave/) level = 3
	    if (level == 3 && /avx512f/&&/avx512bw/&&/avx512cd/&&/avx512dq/&&/avx512vl/) level = 4
	    if (level > 0) { print "linux-xanmod-edge-x64v" level; exit level + 1 }
	    exit 1
	}'
}

################################################################################
#
# Setup
#
apt install apt-transport-https curl -y
[ -f /usr/share/keyrings/xanmod-kernel.gpg ] && rm -f /usr/share/keyrings/xanmod-kernel.gpg
curl -fsSL https://dl.xanmod.org/gpg.key | gpg --dearmor -o /usr/share/keyrings/xanmod-kernel.gpg
echo "deb [signed-by=/usr/share/keyrings/xanmod-kernel.gpg arch=amd64] https://deb.xanmod.org releases main"| tee /etc/apt/sources.list.d/xanmod-kernel.list
apt update
apt install `get_package` -y
exit $?


