#!/bin/bash
#
# xanmod-edge-installer is a simple installer for the Xanmod Edge kernel.
# 
# Copyright (C) 2022 Alan Doyle
#
# https://github.com/alandoyle/helper-scripts/
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi

################################################################################
#
# Setup
#
apt install apt-transport-https curl -y
curl -fsSL https://dl.xanmod.org/gpg.key | gpg --dearmor -o /usr/share/keyrings/xanmod-kernel.gpg
echo "deb [signed-by=/usr/share/keyrings/xanmod-kernel.gpg arch=amd64] https://deb.xanmod.org releases main"| tee /etc/apt/sources.list.d/xanmod-kernel.list
apt update
apt install linux-xanmod-edge -y
